import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Nonton Kuy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <Link href="/" className="logo">NontonKuy</Link>
          <div className="nav-links">
            <Link href="/">Home</Link>
            <form action="">
              <input type="text" className="search-bar" placeholder="Search" />
              <button type="submit"></button>
            </form>
            <Link href="/pages/theaters">Theaters</Link>
            <Link href="/pages/coming-soon">Coming Soon</Link>
            <Link href="/pages/now-showing">Now Showing</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
